language: python
python:
- 3.5
- 2.7

install:
 - sudo apt-get install imagemagick
 - pip install ipython

script:
 - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
   email:
     - mag_dex@o2.pl